name: FTP Deploy

on:
  push:
    branches:
      - main  # Remplacez 'main' par le nom de la branche que vous souhaitez déployer

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: files.000webhost.com
        username: bozusite
        password: C>3Gmt-4_2h3Fp)/
        server-dir: /public_html/Cars/
